[package]
name = "rbcsv"
version = "0.1.0"
edition = "2021"
authors = ["fujitani sora <fujitanisora0414@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
csv = "1.3.1"
magnus = { version = "0.6.2" }
